services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clipkit
    volumes:
      - pg_vol:/var/lib/postgresql/data
    networks:
      - clipkit
  clipkit:
    container_name: clipkit
    restart: always
    image: ghcr.io/rdcsq/clipkit:main
    environment:
      DISCORD_CLIENT_ID: something
      DISCORD_CLIENT_SECRET: something
      DATABASE_URL: postgres://postgres:password@postgres:5432/clipkit?sslmode=disable
      JWT_ACCESS_SECRET: a
      JWT_REFRESH_SECRET: b
      BASE_URL: http://localhost:3000
      S3_PUBLIC_URL: url
      S3_USE_PATH_STYLE_URLS: false
      S3_ENDPOINT: endpoint
      S3_BUCKET: bucket
      S3_REGION: auto
      S3_ACCESS_KEY: a
      S3_SECRET_ACCESS_KEY: b
      FFMPEG_PATH: /app/ffmpeg/ffmpeg # you have to provide your own ffmpeg build
      TEMP_FOLDER: /tmp
    volumes:
      - ./ffmpeg:/app/ffmpeg
    networks:
      - clipkit

volumes:
  pg_vol:


networks:
  clipiit:
